/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motorshop;

/**
 *
 * @author aniket
 */
public class accDetail extends javax.swing.JFrame {

    /**
     * Creates new form accDetail
     */
    public accDetail() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemrevenueButton = new javax.swing.JButton();
        totalrevenueButton = new javax.swing.JToggleButton();
        databaseButton = new javax.swing.JToggleButton();
        orderButton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        itemrevenueButton.setText("Show Item Revenue Details");
        itemrevenueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemrevenueButtonMouseClicked(evt);
            }
        });
        getContentPane().add(itemrevenueButton);
        itemrevenueButton.setBounds(170, 200, 199, 52);

        totalrevenueButton.setText("Show Total Revenue");
        totalrevenueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalrevenueButtonMouseClicked(evt);
            }
        });
        getContentPane().add(totalrevenueButton);
        totalrevenueButton.setBounds(170, 290, 199, 47);

        databaseButton.setText("Show Database");
        databaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databaseButtonMouseClicked(evt);
            }
        });
        getContentPane().add(databaseButton);
        databaseButton.setBounds(170, 120, 199, 47);

        orderButton.setText("Show Items To Order");
        orderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderButtonMouseClicked(evt);
            }
        });
        getContentPane().add(orderButton);
        orderButton.setBounds(170, 370, 199, 47);

        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 30, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/aniket/NetBeansProjects/motorshop/Images/check.jpg")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    UI u = new UI();
    this.dispose();
    u.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void databaseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseButtonMouseClicked
        // TODO add your handling code here:
    DatabaseTable d = new DatabaseTable() ;
    this.dispose();
    d.setVisible(true);
        
    }//GEN-LAST:event_databaseButtonMouseClicked

    private void itemrevenueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemrevenueButtonMouseClicked
        // TODO add your handling code here:
    search s = new search();
    this.dispose();
    s.setVisible(true); 
    }//GEN-LAST:event_itemrevenueButtonMouseClicked

    private void totalrevenueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalrevenueButtonMouseClicked
        // TODO add your handling code here:
    totalrevenueTable t = new totalrevenueTable();
    this.dispose();
    t.setVisible(true);
    }//GEN-LAST:event_totalrevenueButtonMouseClicked

    private void orderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseClicked
        // TODO add your handling code here:
    orderTable o = new orderTable();
    this.dispose();
    o.setVisible(true);  
    }//GEN-LAST:event_orderButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton databaseButton;
    private javax.swing.JButton itemrevenueButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton orderButton;
    private javax.swing.JToggleButton totalrevenueButton;
    // End of variables declaration//GEN-END:variables
}
