/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package motorshop;

import javax.swing.*;
import java.sql.*;
import java.text.DateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author aniket
 */
public class manage extends javax.swing.JFrame {

    /**
     * Creates new form manage
     */
    public manage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        itemNameTF = new javax.swing.JTextField();
        thresholdTF = new javax.swing.JTextField();
        vendorTF = new javax.swing.JTextField();
        quantityTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        sellTF = new javax.swing.JTextField();
        costTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        soldTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        itemIdTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_ID", "Item_Name", "Vendor_Name", "Quantity", "Threshold value", "CostPrice", "SellPrice", "Sold", "Date"
            }
        ));
        table.setGridColor(java.awt.Color.white);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(63, 314, 792, 140);

        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 250, 120, 50);

        itemNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(itemNameTF);
        itemNameTF.setBounds(130, 60, 78, 27);

        thresholdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdTFActionPerformed(evt);
            }
        });
        getContentPane().add(thresholdTF);
        thresholdTF.setBounds(420, 60, 98, 27);
        getContentPane().add(vendorTF);
        vendorTF.setBounds(119, 126, 88, 27);
        getContentPane().add(quantityTF);
        quantityTF.setBounds(416, 12, 75, 27);
        getContentPane().add(dateTF);
        dateTF.setBounds(823, 120, 54, 27);
        getContentPane().add(sellTF);
        sellTF.setBounds(823, 12, 54, 27);

        costTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTFActionPerformed(evt);
            }
        });
        getContentPane().add(costTF);
        costTF.setBounds(430, 120, 84, 27);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Item_ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(54, 17, 55, 18);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Item_Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 60, 80, 18);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Vendor Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 131, 97, 18);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(344, 17, 63, 18);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Threshold Value");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 70, 115, 18);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("CostPrice");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(321, 131, 70, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("SellPrice");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(751, 17, 63, 18);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 125, 35, 18);

        soldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldTFActionPerformed(evt);
            }
        });
        getContentPane().add(soldTF);
        soldTF.setBounds(820, 70, 54, 27);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Sold");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(760, 70, 40, 18);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(12, 49, 0, 0);

        jButton4.setText("Add");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 190, 90, 40);

        itemIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdTFActionPerformed(evt);
            }
        });
        getContentPane().add(itemIdTF);
        itemIdTF.setBounds(140, 10, 66, 27);

        jButton2.setText("Home");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 490, 230, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon("/home/aniket/NetBeansProjects/motorshop/Images/check.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-50, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costTFActionPerformed

    private void itemNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTFActionPerformed

    private void thresholdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thresholdTFActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Connection conn = null;
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        
        String[] al = new String[9];
        
        for ( int count = 0 ; count < model.getRowCount() ; count++ ){
            for ( int r = 0 ; r<9 ; r++ )
                al[r] = (String)table.getValueAt(count,r);
try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root" ,"123");
                System.out.println("Connected");
                
                String sql = "INSERT INTO stock(Item_ID,Item_Name,VendorName,Quantity,ThresholdValue,CostPrice,SellPrice,Sold,Revenue,Date,GiveOrder) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,al[0]);
                pst.setString(2,al[1]);
                pst.setString(3,al[2]);
                pst.setString(4,al[3]);
                pst.setString(5,al[4]);
                pst.setString(6,al[5]);
                pst.setString(7,al[6]);
                pst.setString(8,al[7]);   
                int p  = Integer.parseInt(al[6])-Integer.parseInt(al[5]) ;
                int q  = Integer.parseInt(al[7]) ;
                int revenue = p * q ;
                int g = Integer.parseInt(al[3])-Integer.parseInt(al[7]) ;
                int t = Integer.parseInt(al[4]);
                pst.setString(9,  Integer.toString (revenue) ) ;
                pst.setString(10,al[8]);
                if (t>=g)
                    pst.setString(11,"Yes");
                else
                    pst.setString(11,"No");
                
                pst.execute();
           
                
                
            } catch (Exception e){
                System.out.println(e);
            }
        }

itemIdTF.setText(null);
itemNameTF.setText(null);
vendorTF.setText(null);
quantityTF.setText(null);
thresholdTF.setText(null);
costTF.setText(null);
sellTF.setText(null);
soldTF.setText(null);
dateTF.setText(null);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        Object[] row = new Object[11];
        
        row[0] = itemIdTF.getText();
        row[1] = itemNameTF.getText();
        row[2] = vendorTF.getText();
        row[3] = quantityTF.getText();
        row[4] = thresholdTF.getText();
        row[5] = costTF.getText();
        row[6] = sellTF.getText();
        row[7] = soldTF.getText();
        row[8] = dateTF.getText();
        model.addRow(row);
    }//GEN-LAST:event_jButton4MouseClicked

    private void itemIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdTFActionPerformed

    private void soldTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldTFActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    UI u = new UI();
    this.dispose();
    u.setVisible(true); 
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costTF;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField itemIdTF;
    private javax.swing.JTextField itemNameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JTextField sellTF;
    private javax.swing.JTextField soldTF;
    private javax.swing.JTable table;
    private javax.swing.JTextField thresholdTF;
    private javax.swing.JTextField vendorTF;
    // End of variables declaration//GEN-END:variables
}
